export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
export const FETCH_NEXT = "FETCH_NEXT";
export const FETCH_PREVIOUS = "FETCH_PREVIOUS";
export const NOMINATE_MOVIE = "NOMINATE_MOVIE";
export const REMOVE_NOMINEE = "REMOVE_NOMINEE";
